[phases.setup]
commands = ["apt-get update && apt-get install -y php-cli php-mysql composer"]

[phases.build]
commands = ["composer install"]

[phases.start]
commands = ["php -S 0.0.0.0:$PORT -t ."]

